package tampilan;

import pengelola.PenggunaPengelola;
import javax.swing.JOptionPane;

public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    private final PenggunaPengelola penggunaPengelola;

    public LoginFrame() {
        initComponents();

        // panel login gelap semi transparan
        pnlLogin.setOpaque(true);
        pnlLogin.setBackground(new java.awt.Color(0, 0, 0, 140)); // 0–255, 140 = agak transparan

        penggunaPengelola = new PenggunaPengelola();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpDasar = new javax.swing.JLayeredPane();
        lblBackground = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblJudulLogin = new javax.swing.JLabel();
        lblNamaPengguna = new javax.swing.JLabel();
        txtNamaPengguna = new javax.swing.JTextField();
        lblKataSandi = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        btnMasuk = new javax.swing.JButton();
        pwdKataSandi = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lpDasar.setBackground(new java.awt.Color(255, 255, 0));
        lpDasar.setOpaque(true);
        lpDasar.setPreferredSize(new java.awt.Dimension(960, 600));

        lblBackground.setBackground(new java.awt.Color(255, 0, 51));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/_Modern Login Page Desktop Prototype.png"))); // NOI18N

        pnlLogin.setBackground(new java.awt.Color(0, 0, 0, 140));
        pnlLogin.setPreferredSize(new java.awt.Dimension(320, 360));

        lblJudulLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulLogin.setText("LOGIN");

        lblNamaPengguna.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaPengguna.setText("Username");

        lblKataSandi.setForeground(new java.awt.Color(255, 255, 255));
        lblKataSandi.setText("Password");

        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnMasuk.setText("Masuk");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });

        pwdKataSandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdKataSandiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdKataSandi)
                    .addComponent(txtNamaPengguna)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(btnMasuk))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJudulLogin)
                            .addComponent(lblNamaPengguna)
                            .addComponent(lblKataSandi))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulLogin)
                .addGap(48, 48, 48)
                .addComponent(lblNamaPengguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lblKataSandi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnMasuk))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        lpDasar.setLayer(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpDasar.setLayer(pnlLogin, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout lpDasarLayout = new javax.swing.GroupLayout(lpDasar);
        lpDasar.setLayout(lpDasarLayout);
        lpDasarLayout.setHorizontalGroup(
            lpDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpDasarLayout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(lpDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lpDasarLayout.setVerticalGroup(
            lpDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpDasarLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(lpDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lpDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lpDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed

        String namaPengguna = txtNamaPengguna.getText().trim();
        String kataSandi = new String(pwdKataSandi.getPassword());

        if (namaPengguna.isEmpty() || kataSandi.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Username dan password wajib diisi.",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            boolean berhasil = penggunaPengelola.validasiLogin(namaPengguna, kataSandi);

            if (berhasil) {
                // ambil objek Pengguna yang berhasil login
                Pengguna pengguna = penggunaPengelola.cariPenggunaByUsername(namaPengguna);
                // nama method di atas kamu sesuaikan ya

                JOptionPane.showMessageDialog(this,
                        "Login berhasil. Selamat datang, " + namaPengguna + "!",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);

                this.dispose();

                // kirim objek pengguna ke MenuUtamaFrame
                new MenuUtamaFrame(pengguna).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this,
                        "Username atau password salah.",
                        "Gagal Login", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);   // atau this.dispose(); kalau cuma nutup form ini
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void pwdKataSandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdKataSandiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdKataSandiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblJudulLogin;
    private javax.swing.JLabel lblKataSandi;
    private javax.swing.JLabel lblNamaPengguna;
    private javax.swing.JLayeredPane lpDasar;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField pwdKataSandi;
    private javax.swing.JTextField txtNamaPengguna;
    // End of variables declaration//GEN-END:variables
}
