package tampilan;

import entitas.Pengguna;

import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.JComponent;
import java.awt.Graphics;
import javax.swing.JOptionPane;
import javax.swing.Box;

public class MenuUtamaFrame extends javax.swing.JFrame {
    
    private Pengguna penggunaLogin;   // nyimpen user yg lagi login
    

    /**
     * Creates new form MenuUtamaFrame
     */
    public MenuUtamaFrame() {
        // konstruktor DEFAULT, buat design preview
        initComponents();

        // ===== Warna bar: ungu gelap semi modern =====
        mnBarUtama.setBorderPainted(false);
        mnBarUtama.setOpaque(true);

        mnBarUtama.setUI(new BasicMenuBarUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                g.setColor(new java.awt.Color(30, 0, 60)); // ungu gelap
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        });

        // ===== Warna teks menu putih =====
        mnLogo.setForeground(java.awt.Color.WHITE);
        mnProduk.setForeground(java.awt.Color.WHITE);
        mnKategori.setForeground(java.awt.Color.WHITE);
        mnLaporan.setForeground(java.awt.Color.WHITE);
        mnKeluar.setForeground(java.awt.Color.WHITE);
        mnPengguna.setForeground(java.awt.Color.WHITE);

        // font boleh tetap yang tadi, kalau mau:
        java.awt.Font fontMenu = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14);
        mnLogo.setFont(fontMenu);
        mnProduk.setFont(fontMenu);
        mnKategori.setFont(fontMenu);
        mnLaporan.setFont(fontMenu);
        mnKeluar.setFont(fontMenu);
        mnPengguna.setFont(fontMenu);

        // ===== Geser menu Pengguna ke kanan (kode yg lama tetap) =====
        javax.swing.JMenuBar bar = getJMenuBar();
        bar.remove(mnPengguna);
        bar.add(javax.swing.Box.createHorizontalGlue());
        bar.add(mnPengguna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpDasar = new javax.swing.JLayeredPane();
        lblSambutan = new javax.swing.JLabel();
        lblNamaApp = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        pnlInfoLogin = new javax.swing.JPanel();
        lblJudulInfoLogin = new javax.swing.JLabel();
        lblNamaPengguna = new javax.swing.JLabel();
        txtNamaPengguna = new javax.swing.JTextField();
        lblPeran = new javax.swing.JLabel();
        txtPeran = new javax.swing.JTextField();
        mnBarUtama = new javax.swing.JMenuBar();
        mnLogo = new javax.swing.JMenu();
        mnPengguna = new javax.swing.JMenu();
        mnProduk = new javax.swing.JMenu();
        mnKategori = new javax.swing.JMenu();
        mnLaporan = new javax.swing.JMenu();
        mnKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lpDasar.setBackground(new java.awt.Color(255, 255, 0));
        lpDasar.setOpaque(true);
        lpDasar.setPreferredSize(new java.awt.Dimension(960, 560));

        lblSambutan.setBackground(new java.awt.Color(204, 255, 255));
        lblSambutan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSambutan.setForeground(new java.awt.Color(255, 255, 255));
        lblSambutan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSambutan.setText("SELAMAT DATANG DI");

        lblNamaApp.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNamaApp.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaApp.setText("INVENTORIKU");
        lblNamaApp.setToolTipText("");
        lblNamaApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblBackground.setBackground(new java.awt.Color(255, 0, 51));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/_Background polos.png"))); // NOI18N

        pnlInfoLogin.setBackground(new java.awt.Color(0, 0, 0, 140));
        pnlInfoLogin.setPreferredSize(new java.awt.Dimension(500, 260));
        pnlInfoLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudulInfoLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudulInfoLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulInfoLogin.setText("INFO LOGIN");
        lblJudulInfoLogin.setAlignmentX(20.0F);
        lblJudulInfoLogin.setAlignmentY(20.0F);
        pnlInfoLogin.add(lblJudulInfoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblNamaPengguna.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNamaPengguna.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaPengguna.setText("Nama Pengguna");
        lblNamaPengguna.setAlignmentX(20.0F);
        lblNamaPengguna.setAlignmentY(70.0F);
        pnlInfoLogin.add(lblNamaPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, -1, -1));
        pnlInfoLogin.add(txtNamaPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 104, 396, -1));

        lblPeran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPeran.setForeground(new java.awt.Color(255, 255, 255));
        lblPeran.setText("Peran");
        pnlInfoLogin.add(lblPeran, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, -1, -1));
        pnlInfoLogin.add(txtPeran, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 167, 396, -1));

        lpDasar.setLayer(lblSambutan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpDasar.setLayer(lblNamaApp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpDasar.setLayer(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpDasar.setLayer(pnlInfoLogin, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout lpDasarLayout = new javax.swing.GroupLayout(lpDasar);
        lpDasar.setLayout(lpDasarLayout);
        lpDasarLayout.setHorizontalGroup(
            lpDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSambutan, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblNamaApp, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblBackground)
            .addGroup(lpDasarLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(pnlInfoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lpDasarLayout.setVerticalGroup(
            lpDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpDasarLayout.createSequentialGroup()
                .addGroup(lpDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lpDasarLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblSambutan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lpDasarLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblNamaApp))
                    .addGroup(lpDasarLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(pnlInfoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblBackground))
                .addGap(440, 440, 440))
        );

        mnBarUtama.setBackground(new java.awt.Color(255, 255, 255));
        mnBarUtama.setForeground(new java.awt.Color(255, 255, 255));
        mnBarUtama.setPreferredSize(new java.awt.Dimension(960, 40));

        mnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/logo_32px.png"))); // NOI18N
        mnBarUtama.add(mnLogo);

        mnPengguna.setText("Pengguna");
        mnBarUtama.add(mnPengguna);

        mnProduk.setText("Produk");
        mnBarUtama.add(mnProduk);

        mnKategori.setText("Kategori");
        mnBarUtama.add(mnKategori);

        mnLaporan.setText("Laporan");
        mnBarUtama.add(mnLaporan);

        mnKeluar.setText("Keluar");
        mnBarUtama.add(mnKeluar);

        setJMenuBar(mnBarUtama);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lpDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lpDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblJudulInfoLogin;
    private javax.swing.JLabel lblNamaApp;
    private javax.swing.JLabel lblNamaPengguna;
    private javax.swing.JLabel lblPeran;
    private javax.swing.JLabel lblSambutan;
    private javax.swing.JLayeredPane lpDasar;
    private javax.swing.JMenuBar mnBarUtama;
    private javax.swing.JMenu mnKategori;
    private javax.swing.JMenu mnKeluar;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenu mnLogo;
    private javax.swing.JMenu mnPengguna;
    private javax.swing.JMenu mnProduk;
    private javax.swing.JPanel pnlInfoLogin;
    private javax.swing.JTextField txtNamaPengguna;
    private javax.swing.JTextField txtPeran;
    // End of variables declaration//GEN-END:variables
}
