/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author ACER
 */
public class PenggunaFrame extends javax.swing.JFrame {

    /**
     * Creates new form PenggunaFrame
     */
    public PenggunaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpDasar = new javax.swing.JLayeredPane();
        lblBackground = new javax.swing.JLabel();
        mnBarUtama = new javax.swing.JMenuBar();
        mnLogo = new javax.swing.JMenu();
        mnPengguna = new javax.swing.JMenu();
        mnProduk = new javax.swing.JMenu();
        mnKategori = new javax.swing.JMenu();
        mnLaporan = new javax.swing.JMenu();
        mnKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lpDasar.setBackground(new java.awt.Color(255, 255, 0));
        lpDasar.setOpaque(true);
        lpDasar.setPreferredSize(new java.awt.Dimension(960, 560));

        lblBackground.setBackground(new java.awt.Color(255, 0, 51));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/_Background polos.png"))); // NOI18N

        lpDasar.setLayer(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpDasarLayout = new javax.swing.GroupLayout(lpDasar);
        lpDasar.setLayout(lpDasarLayout);
        lpDasarLayout.setHorizontalGroup(
            lpDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground)
        );
        lpDasarLayout.setVerticalGroup(
            lpDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpDasarLayout.createSequentialGroup()
                .addComponent(lblBackground)
                .addGap(440, 440, 440))
        );

        mnBarUtama.setBackground(new java.awt.Color(255, 255, 255));
        mnBarUtama.setForeground(new java.awt.Color(255, 255, 255));
        mnBarUtama.setPreferredSize(new java.awt.Dimension(960, 40));

        mnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/logo_32px.png"))); // NOI18N
        mnBarUtama.add(mnLogo);

        mnPengguna.setText("Pengguna");
        mnBarUtama.add(mnPengguna);

        mnProduk.setText("Produk");
        mnBarUtama.add(mnProduk);

        mnKategori.setText("Kategori");
        mnBarUtama.add(mnKategori);

        mnLaporan.setText("Laporan");
        mnBarUtama.add(mnLaporan);

        mnKeluar.setText("Keluar");
        mnBarUtama.add(mnKeluar);

        setJMenuBar(mnBarUtama);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lpDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lpDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenggunaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenggunaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenggunaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenggunaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenggunaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLayeredPane lpDasar;
    private javax.swing.JMenuBar mnBarUtama;
    private javax.swing.JMenu mnKategori;
    private javax.swing.JMenu mnKeluar;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenu mnLogo;
    private javax.swing.JMenu mnPengguna;
    private javax.swing.JMenu mnProduk;
    // End of variables declaration//GEN-END:variables
}
